services:
  pgbouncer:
    image: edoburu/pgbouncer:1.18.0
    depends_on:
      - postgres
    environment:
      DATABASE_URL: "postgres://neops:${POSTGRES_PASSWORD}@postgres:5432/neops"
      POOL_MODE: "transaction"
      LISTEN_PORT: 6432
      ADMIN_USERS: neops
      DEFAULT_POOL_SIZE: "50"
      MAX_CLIENT_CONN: "3000"
      SERVER_RESET_QUERY_ALWAYS: "1"
      RESERVE_POOL_SIZE: "1000"
      RESERVE_POOL_TIMEOUT: "10"
      # SERVER_LIFETIME: "120"
      # SERVER_IDLE_TIMEOUT: "60"
      # QUERY_WAIT_TIMEOUT: "30"
      # CLIENT_IDLE_TIMEOUT: "300"
      # IDLE_TRANSACTION_TIMEOUT: "120"
    expose:
      - 6432
    networks:
      - private
    restart: "on-failure"

  backend:
    depends_on:
      - pgbouncer
    environment:
      DATABASE_URL: "postgres://neops:${POSTGRES_PASSWORD}@pgbouncer:6432/neops"
      DATABASE_HEALTH_URL: "postgres://neops:${POSTGRES_PASSWORD}@postgres:5432/neops"
      PGBOUNCER_TRANSACTION: "True"

  worker:
    depends_on:
      - pgbouncer
    environment:
      DATABASE_URL: "postgres://neops:${POSTGRES_PASSWORD}@pgbouncer:6432/neops"
      PGBOUNCER_TRANSACTION: "True"

  beat:
    depends_on:
      - pgbouncer
    environment:
      DATABASE_URL: "postgres://neops:${POSTGRES_PASSWORD}@pgbouncer:6432/neops"
      PGBOUNCER_TRANSACTION: "True"
