services:
  frontend:
    deploy:
      replicas: ${NEOPS_FRONTEND_REPLICAS:-1}
      resources:
        limits:
          memory: "${NEOPS_FRONTEND_MEMORY:-500M}"

  backend:
    deploy:
      replicas: ${NEOPS_BACKEND_REPLICAS:-1}
      resources:
        limits:
          memory: "${NEOPS_BACKEND_MEMORY:-1G}"

  worker:
    deploy:
      replicas: ${NEOPS_WORKER_REPLICAS:-3}
      resources:
        limits:
          memory: "${NEOPS_WORKER_MEMORY:-1G}"

  elasticsearch:
    deploy:
      resources:
        limits:
          memory: "${NEOPS_ELASTICSEARCH_MEMORY:-2G}"