services:
  web-client:
    expose:
      - "80"
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.http.routers.neops-webclient-http-router.entrypoints: http
      traefik.http.routers.neops-webclient-http-router.rule: Host(`${PUBLIC_WEBCLIENT_HOSTNAME}`)
      traefik.http.services.neops-webclient-service.loadbalancer.server.port: "80"
      traefik.http.services.neops-webclient-service.loadbalancer.server.scheme: http

  frontend:
    expose:
      - "80"
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.http.routers.neops-frontend-http-router.entrypoints: http
      traefik.http.routers.neops-frontend-http-router.rule: Host(`${PUBLIC_NEOPS_HOSTNAME}`)
      traefik.http.services.neops-frontend-service.loadbalancer.server.port: "80"
      traefik.http.services.neops-frontend-service.loadbalancer.server.scheme: http

  backend:
    expose:
      - "8000"
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.http.routers.neops-backend-http-router.entrypoints: http
      traefik.http.routers.neops-backend-http-router.rule: Host(`${PUBLIC_NEOPS_HOSTNAME}`) && (Path(`/graphql`) || Path(`/graphql/`) || PathPrefix(`/graphiql/`) || PathPrefix(`/admin/`) || PathPrefix(`/djstatic`) || PathPrefix(`/webhook/`))
      traefik.http.services.neops-backend-service.loadbalancer.server.port: "8000"
      traefik.http.services.neops-backend-service.loadbalancer.server.scheme: http

  flower:
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.http.routers.flower-http-router.entrypoints: http
      traefik.http.routers.flower-http-router.rule: Host(`${PUBLIC_FLOWER_HOSTNAME}`)
      traefik.http.services.flower-service.loadbalancer.server.port: "5556"
      traefik.http.services.flower-service.loadbalancer.server.scheme: http

  kibana:
    networks:
      - traefik
    labels:
      traefik.enable: "true"
      traefik.docker.network: traefik
      traefik.http.routers.kibana-http-router.entrypoints: http
      traefik.http.routers.kibana-http-router.rule: Host(`${PUBLIC_KIBANA_HOSTNAME}`)
      traefik.http.services.kibana-service.loadbalancer.server.port: "5601"
      traefik.http.services.kibana-service.loadbalancer.server.scheme: http

networks:
  traefik:
    external: true
