services:
  frontend:
    deploy:
      resources:
        limits:
          memory: "${NEOPS_FRONTEND_MEMORY:-500M}"

  backend:
    deploy:
      resources:
        limits:
          cpus: "${NEOPS_BACKEND_MEMORY:-1G}"
          memory: 500M

  worker:
    deploy:
      resources:
        limits:
          cpus: "${NEOPS_WORKER_MEMORY:-1G}"
          memory: 500M
