# docker-compose file for development with django and vue.js running directly on the host
version: "3.7"

services:
  redis:
    image: redis:5-alpine
    ports:
      # we run redis on a non-standard port to avoid collision with a locally installed postgres
      - "6380:6379"
    networks:
      - redis-net
   
  etcd:
    image: quay.io/coreos/etcd
    ports:
      - 2379:2379
      - 2380:2380
      - 4001:4001
    command: sh -c 'etcd -listen-client-urls http://0.0.0.0:2379 -advertise-client-urls http://etcd-srv:2379'

  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: unsafe
    volumes:
      - ./data/postgres_dev:/var/lib/postgresql/data
    ports:
      # we run postgres on a non-standard port to avoid collision with a locally installed postgres
      - 5433:5432

  flower:
    image: saxix/flower
    command:
      ["celery", "flower", "--broker=redis://redis:6379/0", "--port=5555"]
    ports:
      - 5555:5555
    networks:
      - redis-net
    links:
      - redis

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - cluster.routing.allocation.disk.threshold_enabled=false
      - indices.query.bool.max_clause_count=2048
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.1
    ports:
      - 5601:5601

  keycloak_postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - keycloak:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres

  keycloak:
    image: jboss/keycloak:6.0.1
    environment:
      KEYCLOAK_USER: "admin"
      KEYCLOAK_PASSWORD: "HelloWorld"
      DB_VENDOR: "POSTGRES"
      DB_ADDR: "keycloak_postgres"
      DB_DATABASE: "keycloak"
      DB_USER: "keycloak"
      DB_PASSWORD: "password"
    ports:
      - "8081:8080"
    #volumes:
    #  - "./data/keycloak/standalone:/opt/jboss/keycloak/standalone"
    depends_on:
      - keycloak_postgres

volumes:
  elasticsearch:
    driver: local
  keycloak:
    driver: local

networks:
  redis-net:
    driver: "bridge"
