services:
  web-client-sgw:
    image: quay.io/zebbra/neops-web-client:${NEOPS_WEBCLIENT_IMAGE_TAG:-0.1}
    environment:
      FRONTEND_GRAPHQL_ENDPOINT: ${SECURE_GW_API_URL}
    restart: "on-failure"

  secure-gw:
    image: quay.io/zebbra/neops-gql-gtw:${NEOPS_SECURE_GW_IMAGE_TAG:-0.1}
    environment:
      - PATH_TO_RULES=config/gql_gw_rules.json
      - GRAPHQL_ENDPOINT_NEOPS=${NEOPS_API_URL}
      - STATIC_AUTH_TOKEN=${STATIC_AUTH_TOKEN}
    volumes:
      - ./config/gql_gw_rules.json/:/usr/src/app/config/gql_gw_rules.json
    restart: "on-failure"
