from __future__ import annotations

import json
from pathlib import Path

from neops_compose.env import Env
from neops_compose.paths import Paths
from neops_compose.scenario import Scenario
from neops_compose.secrets import private_dir, read_keycloak_client_secret, write_secret
from neops_compose.traefik_model import build_traefik, dynamic_config, static_config
from neops_compose.urls import PublicUrl

KEYCLOAK_REALM = "neops"
KEYCLOAK_CLIENT_ID = "neops-auth"
KEYCLOAK_PROVIDER_ID = "keycloak"
# Core reads these with a default that only applies when the variable is ABSENT:
# an empty EMAIL_URL is an invalid email schema, not "use consolemail://".
# RATELIMIT_IP_META_KEY only means something behind a proxy that overwrites the header,
# so it stays the operator's call in .env; compose.traefik.yaml sets it for its own proxy.
OPTIONAL_CORE_KEYS = ("SENTRY_DSN", "SENTRY_ENVIRONMENT", "EMAIL_URL", "RATELIMIT_IP_META_KEY")


class MissingSecret(Exception):
    pass


class RenderError(Exception):
    pass


def render(env: Env, scenario: Scenario, paths: Paths) -> list[Path]:
    """Rebuild generated/ from .env, writing files in place.

    Bind-mounted files inside a running container must see updates on their existing
    inode, so files are opened and overwritten rather than the directory being wiped
    and recreated. Deterministic; removes what the scenario no longer needs.
    """
    out = paths.generated
    private_dir(out)
    written: set[Path] = set()

    def emit(rel: str, text: str, mode: int = 0o600) -> None:
        p = out / rel
        try:
            write_secret(p, text.encode(), mode=mode)
        except IsADirectoryError as exc:
            raise RenderError(
                f"{p} is a directory; docker created it because the stack was started "
                f"before ./neops render. Stop the stack and remove it: sudo rm -rf {p}"
            ) from exc
        written.add(p)

    emit("cms.env", cms_env(env, scenario))
    if scenario.proxy == "traefik":
        cfg = build_traefik(env, scenario)
        emit("traefik/traefik.yml", _yaml_json(static_config(cfg)))
        emit("traefik/dynamic.yml", _yaml_json(dynamic_config(cfg)))
    if scenario.keycloak:
        emit("keycloak.env", f"KC_HTTP_RELATIVE_PATH={keycloak_relative_path(env)}\n")
        # The Keycloak container (uid 1000) reads this straight off the bind mount;
        # the 0700 generated/keycloak/ still hides it from other host users.
        emit("keycloak/realm.json", json.dumps(keycloak_realm(env, paths), indent=2) + "\n", mode=0o644)
    if scenario.oidc:
        # 0600 is fine here: neops-core reads it running as root (no USER in its
        # Dockerfile). A non-root core image would need 0644, like realm.json above.
        emit("providers.json", json.dumps(providers(env, scenario, paths), indent=2) + "\n")
    _remove_stale(out, written)
    return sorted(written)


def _remove_stale(out: Path, written: set[Path]) -> None:
    for p in list(out.rglob("*")):
        if p.is_file() and p not in written:
            p.unlink()
    dirs = sorted((p for p in out.rglob("*") if p.is_dir()), key=lambda p: len(p.parts), reverse=True)
    for d in dirs:
        if not any(d.iterdir()):
            d.rmdir()


def _yaml_json(doc: dict) -> str:
    # JSON is valid YAML; Traefik parses the .yml extension with a YAML reader.
    return json.dumps(doc, indent=2) + "\n"


def cms_env(env: Env, scenario: Scenario) -> str:
    web = PublicUrl.parse(env.require("NEOPS_WEB_URL"))
    cms = PublicUrl.parse(env.require("NEOPS_CMS_URL"))
    hosts = [cms.host]
    if web.host != cms.host:
        hosts.append(web.host)
    hosts += ["cms", "localhost", "127.0.0.1"]
    lines = [
        "# Generated by ./neops render from .env. Do not edit.",
        f"DJANGO_ALLOWED_HOSTS={','.join(hosts)}",
        f"ACCOUNT_DEFAULT_HTTP_PROTOCOL={web.scheme}",
    ]
    if not web.same_origin(cms):
        lines.append("CORS_ORIGIN_ALLOW_ALL=True")
    if web.scheme == "http":
        # Core defaults both to True outside DEBUG, which makes the admin unusable over
        # plain http (evaluation scenarios only; every TLS overlay leaves these unset).
        lines.append("SESSION_COOKIE_SECURE=False")
        lines.append("CSRF_COOKIE_SECURE=False")
    lines += [f"{key}={env.get(key)}" for key in OPTIONAL_CORE_KEYS if env.is_set(key)]
    return "\n".join(lines) + "\n"


def keycloak_relative_path(env: Env) -> str:
    return PublicUrl.parse(env.require("NEOPS_KEYCLOAK_URL")).path or "/"


def _keycloak_client_secret(paths: Paths) -> str:
    secret = read_keycloak_client_secret(paths.keycloak_client_env)
    if secret is None:
        raise MissingSecret("data/secrets/keycloak-client.env is missing; run ./neops keys")
    return secret


def providers(env: Env, scenario: Scenario, paths: Paths) -> dict:
    if scenario.keycloak:
        rel = keycloak_relative_path(env).rstrip("/")
        entry = {
            "provider_id": KEYCLOAK_PROVIDER_ID,
            "name": "Keycloak",
            "client_id": KEYCLOAK_CLIENT_ID,
            "secret": _keycloak_client_secret(paths),
            "settings": {
                "server_url": f"http://keycloak:8080{rel}/realms/{KEYCLOAK_REALM}/.well-known/openid-configuration"
            },
        }
    else:
        settings: dict[str, object] = {"server_url": env.require("NEOPS_OIDC_DISCOVERY_URL")}
        if env.flag("NEOPS_OIDC_TRUST_EMAIL_WITHOUT_VERIFICATION"):
            settings["trust_email_without_verification"] = True
        entry = {
            "provider_id": env.require("NEOPS_OIDC_PROVIDER_ID"),
            "name": env.require("NEOPS_OIDC_NAME"),
            "client_id": env.require("NEOPS_OIDC_CLIENT_ID"),
            "secret": env.require("NEOPS_OIDC_CLIENT_SECRET"),
            "settings": settings,
        }
    return {"providers": [entry]}


def keycloak_realm(env: Env, paths: Paths) -> dict:
    web = PublicUrl.parse(env.require("NEOPS_WEB_URL"))
    cms = PublicUrl.parse(env.require("NEOPS_CMS_URL"))
    secret = _keycloak_client_secret(paths)
    return {
        "realm": KEYCLOAK_REALM,
        "enabled": True,
        "sslRequired": "external",
        "registrationAllowed": False,
        "clients": [
            {
                "clientId": KEYCLOAK_CLIENT_ID,
                "name": "Neops",
                "enabled": True,
                "protocol": "openid-connect",
                "publicClient": False,
                "clientAuthenticatorType": "client-secret",
                "secret": secret,
                "standardFlowEnabled": True,
                "implicitFlowEnabled": False,
                "directAccessGrantsEnabled": False,
                "serviceAccountsEnabled": False,
                "redirectUris": [f"{cms}/accounts/oidc/{KEYCLOAK_PROVIDER_ID}/login/callback/"],
                "webOrigins": [],
                "attributes": {"post.logout.redirect.uris": f"{web}/*"},
                "defaultClientScopes": ["profile", "email", "roles", "web-origins"],
                "protocolMappers": [
                    {
                        "name": "neops client roles (id+userinfo)",
                        "protocol": "openid-connect",
                        "protocolMapper": "oidc-usermodel-client-role-mapper",
                        "consentRequired": False,
                        "config": {
                            "claim.name": "resource_access.${client_id}.roles",
                            "jsonType.label": "String",
                            "multivalued": "true",
                            "id.token.claim": "true",
                            "access.token.claim": "true",
                            "userinfo.token.claim": "true",
                            "usermodel.clientRoleMapping.clientId": KEYCLOAK_CLIENT_ID,
                        },
                    }
                ],
            }
        ],
    }
