from __future__ import annotations

import json
import shutil
from pathlib import Path

from neops_compose.env import Env
from neops_compose.paths import Paths
from neops_compose.scenario import Scenario
from neops_compose.secrets import private_dir, read_keycloak_client_secret, write_secret
from neops_compose.traefik_model import build_traefik, dynamic_config, static_config
from neops_compose.urls import PublicUrl

KEYCLOAK_REALM = "neops"
KEYCLOAK_CLIENT_ID = "neops-auth"
KEYCLOAK_PROVIDER_ID = "keycloak"


def render(env: Env, scenario: Scenario, paths: Paths) -> list[Path]:
    """Rebuild generated/ from .env. Deterministic; removes what the scenario no longer needs."""
    out = paths.generated
    if out.exists():
        shutil.rmtree(out)
    private_dir(out)
    written: list[Path] = []

    def emit(rel: str, text: str) -> None:
        p = out / rel
        write_secret(p, text.encode())
        written.append(p)

    emit("cms.env", cms_env(env, scenario))
    if scenario.proxy == "traefik":
        cfg = build_traefik(env, scenario)
        emit("traefik/traefik.yml", _yaml_json(static_config(cfg)))
        emit("traefik/dynamic.yml", _yaml_json(dynamic_config(cfg)))
    if scenario.keycloak:
        emit("keycloak.env", f"KC_HTTP_RELATIVE_PATH={keycloak_relative_path(env)}\n")
        emit("keycloak/realm.json", json.dumps(keycloak_realm(env, paths), indent=2) + "\n")
    if scenario.oidc:
        emit("providers.json", json.dumps(providers(env, scenario, paths), indent=2) + "\n")
    return written


def _yaml_json(doc: dict) -> str:
    # JSON is valid YAML; Traefik parses the .yml extension with a YAML reader.
    return json.dumps(doc, indent=2) + "\n"


def cms_env(env: Env, scenario: Scenario) -> str:
    web = PublicUrl.parse(env.require("NEOPS_WEB_URL"))
    cms = PublicUrl.parse(env.require("NEOPS_CMS_URL"))
    hosts = [cms.host]
    if web.host != cms.host:
        hosts.append(web.host)
    hosts += ["cms", "localhost", "127.0.0.1"]
    lines = [
        "# Generated by ./neops render from .env. Do not edit.",
        f"DJANGO_ALLOWED_HOSTS={','.join(hosts)}",
        f"ACCOUNT_DEFAULT_HTTP_PROTOCOL={web.scheme}",
    ]
    if not web.same_origin(cms):
        lines.append("CORS_ORIGIN_ALLOW_ALL=True")
    return "\n".join(lines) + "\n"


def keycloak_relative_path(env: Env) -> str:
    return PublicUrl.parse(env.require("NEOPS_KEYCLOAK_URL")).path or "/"


def providers(env: Env, scenario: Scenario, paths: Paths) -> dict:
    if scenario.keycloak:
        rel = keycloak_relative_path(env).rstrip("/")
        entry = {
            "provider_id": KEYCLOAK_PROVIDER_ID,
            "name": "Keycloak",
            "client_id": KEYCLOAK_CLIENT_ID,
            "secret": read_keycloak_client_secret(paths.keycloak_client_env) or "",
            "settings": {
                "server_url": f"http://keycloak:8080{rel}/realms/{KEYCLOAK_REALM}/.well-known/openid-configuration"
            },
        }
    else:
        entry = {
            "provider_id": env.require("NEOPS_OIDC_PROVIDER_ID"),
            "name": env.require("NEOPS_OIDC_NAME"),
            "client_id": env.require("NEOPS_OIDC_CLIENT_ID"),
            "secret": env.require("NEOPS_OIDC_CLIENT_SECRET"),
            "settings": {"server_url": env.require("NEOPS_OIDC_DISCOVERY_URL")},
        }
    return {"providers": [entry]}


def keycloak_realm(env: Env, paths: Paths) -> dict:
    web = PublicUrl.parse(env.require("NEOPS_WEB_URL"))
    cms = PublicUrl.parse(env.require("NEOPS_CMS_URL"))
    secret = read_keycloak_client_secret(paths.keycloak_client_env) or ""
    return {
        "realm": KEYCLOAK_REALM,
        "enabled": True,
        "sslRequired": "external",
        "registrationAllowed": False,
        "clients": [
            {
                "clientId": KEYCLOAK_CLIENT_ID,
                "name": "NeOps",
                "enabled": True,
                "protocol": "openid-connect",
                "publicClient": False,
                "clientAuthenticatorType": "client-secret",
                "secret": secret,
                "standardFlowEnabled": True,
                "implicitFlowEnabled": False,
                "directAccessGrantsEnabled": False,
                "serviceAccountsEnabled": False,
                "redirectUris": [f"{cms}/accounts/oidc/{KEYCLOAK_PROVIDER_ID}/login/callback/"],
                "webOrigins": [],
                "attributes": {"post.logout.redirect.uris": f"{web}/*"},
                "defaultClientScopes": ["profile", "email", "roles", "web-origins"],
                "protocolMappers": [
                    {
                        "name": "neops client roles (id+userinfo)",
                        "protocol": "openid-connect",
                        "protocolMapper": "oidc-usermodel-client-role-mapper",
                        "consentRequired": False,
                        "config": {
                            "claim.name": "resource_access.${client_id}.roles",
                            "jsonType.label": "String",
                            "multivalued": "true",
                            "id.token.claim": "true",
                            "access.token.claim": "true",
                            "userinfo.token.claim": "true",
                            "usermodel.clientRoleMapping.clientId": KEYCLOAK_CLIENT_ID,
                        },
                    }
                ],
            }
        ],
    }
