global:
  scrape_interval: 30s

scrape_configs:
  - job_name: neops
    metrics_path: /metrics
    static_configs:
      - targets: [cms:8000]

  - job_name: celery
    static_configs:
      - targets: [celery-exporter:9808]

  - job_name: redis
    static_configs:
      - targets: [redis-exporter:9121]

  - job_name: postgres
    static_configs:
      - targets: [postgres-exporter-cms:9187]
        labels: {database: cms}
      - targets: [postgres-exporter-engine:9187]
        labels: {database: engine}

  - job_name: elasticsearch
    static_configs:
      - targets: [elasticsearch-exporter:9114]

  - job_name: victoriametrics
    static_configs:
      - targets: [victoriametrics:8428]

  - job_name: vmalert
    static_configs:
      - targets: [vmalert:8880]
