---
services:
  pnp:
    image: quay.io/zebbra/neops-pnp-guestshell:latest
    restart: "always"
    environment:
      - NEOPS_API_URL=${NEOPS_API_URL}
      - NEOPS_API_KEY=${NEOPS_API_KEY}
      - NEOPS_TASK_NAME=${NEOPS_TASK_NAME}
      # - NEOPS_TASK_MAPPING=${NEOPS_TASK_MAPPING}
      # - PORT=${PORT}
      - PNP_EXT_ADDR=${PNP_EXT_ADDR}
      - PNP_EXT_PORT=${PNP_EXT_PORT}
      - DEVICES_DEFAULT_USERNAME=${DEVICES_DEFAULT_USERNAME}
      - DEVICES_DEFAULT_PW=${DEVICES_DEFAULT_PW}
      - PNP_TEMPLATE=${PNP_TEMPLATE}
      #- LISTEN_INTERFACE=${LISTEN_INTERFACE}
      #- PNP_DEBUG=${PNP_DEBUG}
      #- DEBUG_LEVEL=${DEBUG_LEVEL}
    volumes:
      - ./data/pnp:/pnp/templates/custom
    networks:
      - private
    ports:
      - "${PNP_EXT_PORT}:8081"

networks:
  private:
    driver: bridge
